import React from 'react';
import Head from 'next/head';
import Header from '@/components/Header/Header';
import {
  Box,
  Button,
  Input,
  InputGroup,
  InputRightElement,
  Text,
  useColorModeValue,
} from '@chakra-ui/react';
import { useSelector } from 'react-redux';
import Message from '@/components/Message/Message';

export default function Home() {
  const channel = useSelector((state) => state.channel);
  const bg2 = useColorModeValue('gray.200', '#252329');

  return (
    <>
      <Head>
        <title>Chat - Group</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box width='100%' pl={'320px'} bg={bg2}>
        <Box
          display='flex'
          flexDirection='column'
          justifyContent='space-between'
          height='100vh'
        >
          <Box>
            <Header title={channel?.dataById?.title} />
          </Box>

          <Box
            px={10}
            flex={1}
            py={10}
            display={'flex'}
            alignItems={'flex-end'}
          >
            <Message />
          </Box>

          <Box pb={8} px={9}>
            <InputGroup size='lg'>
              <Input
                pr='4.5rem'
                placeholder='Enter password'
                bg={'#3C393F'}
                border='none'
                fontSize={'sm'}
              />

              <InputRightElement width='4.5rem'>
                <Button size='sm'>Send</Button>
              </InputRightElement>
            </InputGroup>
          </Box>
        </Box>
      </Box>
    </>
  );
}
